# Generated by Django 5.0.3 on 2024-06-02 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_usu', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_resul', models.DateTimeField(default=True)),
                ('estado_resul', models.CharField(max_length=20)),
                ('puntu_resul', models.IntegerField()),
                ('usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.usuario')),
            ],
        ),
    ]
