# Generated by Django 5.0.6 on 2024-07-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0006_perfil_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='email',
            new_name='emailPerfil',
        ),
    ]
