# Generated by Django 5.0.6 on 2024-07-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0007_rename_email_perfil_emailperfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='pais',
        ),
        migrations.AddField(
            model_name='perfil',
            name='comidaFavorita',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
