# Generated by Django 5.0.6 on 2024-07-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0008_remove_perfil_pais_perfil_comidafavorita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fotoPerfil',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
